# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_reglogin', '0003_user_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tasks', models.TextField(max_length=1000)),
                ('apptdate', models.DateField()),
                ('appttime', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apptuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apptuser', to='app_reglogin.User')),
            ],
        ),
    ]
