# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appt', '0002_appointment_apptstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='apptdate',
            field=models.DateField(verbose_name={'input_formats': ('%Y-%m-%d',)}),
        ),
    ]
