# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appt', '0003_auto_20170628_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='apptstatus',
            field=models.CharField(default='pending', max_length=38),
        ),
    ]
